# Benjamin Chappell
# Enum class to represent the cards

from enum import Enum, auto

class Cards(Enum):
    ACE_SPADES = 0
    TWO_SPADES = auto()
    THREE_SPADES = auto()
    FOUR_SPADES = auto()
    FIVE_SPADES = auto()
    SIX_SPADES = auto()
    SEVEN_SPADES = auto()
    EIGHT_SPADES = auto()
    NINE_SPADES = auto()
    TEN_SPADES = auto()
    JACK_SPADES = auto()
    QUEEN_SPADES = auto()
    KING_SPADES = auto()

    ACE_DIAMONDS = auto()
    TWO_DIAMONDS = auto()
    THREE_DIAMONDS = auto()
    FOUR_DIAMONDS = auto()
    FIVE_DIAMONDS = auto()
    SIX_DIAMONDS = auto()
    SEVEN_DIAMONDS= auto()
    EIGHT_DIAMONDS = auto()
    NINE_DIAMONDS = auto()
    TEN_DIAMONDS = auto()
    JACK_DIAMONDS = auto()
    QUEEN_DIAMONDS = auto()
    KING_DIAMONDS = auto()

    ACE_CLUBS = auto()
    TWO_CLUBS = auto()
    THREE_CLUBS = auto()
    FOUR_CLUBS = auto()
    FIVE_CLUBS = auto()
    SIX_CLUBS = auto()
    SEVEN_CLUBS = auto()
    EIGHT_CLUBS = auto()
    NINE_CLUBS = auto()
    TEN_CLUBS = auto()
    JACK_CLUBS = auto()
    QUEEN_CLUBS = auto()
    KING_CLUBS = auto()

    ACE_HEARTS = auto()
    TWO_HEARTS = auto()
    THREE_HEARTS = auto()
    FOUR_HEARTS = auto()
    FIVE_HEARTS = auto()
    SIX_HEARTS = auto()
    SEVEN_HEARTS = auto()
    EIGHT_HEARTS = auto()
    NINE_HEARTS = auto()
    TEN_HEARTS = auto()
    JACK_HEARTS = auto()
    QUEEN_HEARTS = auto()
    KING_HEARTS = auto()